image: selialkile/elixir1.5-phantomjs

before_script:
  - nohup phantomjs --webdriver=8910 --ignore-ssl-errors=true >/dev/null 2>&1 &
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - tail -f mix.exs

mix_tests:
  script:
    - time mix test

variables:
  WEBDRIVER: phantomjs
  WEBDRIVER_HOST: http://localhost
  WEBDRIVER_PORT: "8910"
